[16.0] [FIX] adapt l10n_it_ricevute_bancarie to english naming conventions
saydigital/l10n-italy pull request #2
Opened 2023-03-29 13:37 UTC by primes2h

2023-06-23 08:24 UTC, TonyMasciI commented
ciao @primes2h non mi torna questa PR, hai aggiunto il nuovo modulo rinominato ma non rimuovi il modulo vecchio, non sarebbe il caso eliminarlo?

2023-06-23 10:10 UTC, primes2h commented
> ciao @primes2h non mi torna questa PR, hai aggiunto il nuovo modulo rinominato ma non rimuovi il modulo vecchio, non sarebbe il caso eliminarlo?

Si scusa, errore mio nel rebase.
Adesso dovrebbe essere ok.

2023-08-04 13:20 UTC, TonyMasciI requested changes

2023-08-04 13:20 UTC, TonyMasciI commented on l10n_it_declaration_of_intent/i18n/l10n_it_dichiarazione_intento.pot
> +msgstr ""
Rimuovere questa modifica

2023-08-04 14:17 UTC, primes2h commented
Chiudo in favore di #4

2023-08-04 14:17 UTC, closed without merging